/* postmayne.c generated by valac 0.46.3, the Vala compiler
 * generated from postmayne.vala, do not modify */

/*  Copyright (C) 2019 Steven D. Branson. View the LICENSE file at the top level of this project for more information.  */

#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gtk/gtk.h>
#include <glib-object.h>
#include <libsoup/soup.h>

#define TYPE_MAIN_WINDOW (main_window_get_type ())
#define MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_WINDOW, MainWindow))
#define MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_WINDOW, MainWindowClass))
#define IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_WINDOW))
#define IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_WINDOW))
#define MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_WINDOW, MainWindowClass))

typedef struct _MainWindow MainWindow;
typedef struct _MainWindowClass MainWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _MainWindowPrivate MainWindowPrivate;
enum  {
	MAIN_WINDOW_0_PROPERTY,
	MAIN_WINDOW_NUM_PROPERTIES
};
static GParamSpec* main_window_properties[MAIN_WINDOW_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block1Data Block1Data;

struct _MainWindow {
	GtkWindow parent_instance;
	MainWindowPrivate * priv;
};

struct _MainWindowClass {
	GtkWindowClass parent_class;
};

struct _MainWindowPrivate {
	GtkTextView* response_body_text_view;
	GtkComboBoxText* request_method_combo;
	GtkEntry* url_entry;
	GtkGrid* request_header_grid;
	gint request_header_grid_size;
	GtkEntry* request_body_content_type_entry;
	GtkTextView* request_body_text_view;
};

struct _Block1Data {
	int _ref_count_;
	MainWindow* self;
	GtkButton* header_delete_button;
};

static gint MainWindow_private_offset;
static gpointer main_window_parent_class = NULL;

gint _vala_main (gchar** args,
                 gint args_length1);
GType main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (MainWindow, g_object_unref)
MainWindow* main_window_new (void);
MainWindow* main_window_construct (GType object_type);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender,
                                        gpointer self);
static void main_window_on_send_clicked (MainWindow* self);
static void _main_window_on_send_clicked_gtk_button_clicked (GtkButton* _sender,
                                                      gpointer self);
static void main_window_add_request_header_row (MainWindow* self);
static void _main_window_add_request_header_row_gtk_button_clicked (GtkButton* _sender,
                                                             gpointer self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static void __lambda4_ (Block1Data* _data1_);
static void main_window_remove_request_header_row (MainWindow* self,
                                            GtkWidget* header_delete_button);
static void ___lambda4__gtk_button_clicked (GtkButton* _sender,
                                     gpointer self);
static void main_window_on_http_request_complete (MainWindow* self,
                                           SoupSession* session,
                                           SoupMessage* message);
static void _main_window_on_http_request_complete_soup_session_callback (SoupSession* session,
                                                                  SoupMessage* msg,
                                                                  gpointer self);
static void main_window_finalize (GObject * obj);

static const gchar* MAIN_WINDOW_REQUEST_METHODS[9] = {"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS", "CONNECT", "TRACE"};

static void
_gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender,
                                   gpointer self)
{
#line 10 "src/postmayne.vala"
	gtk_main_quit ();
#line 98 "postmayne.c"
}

gint
_vala_main (gchar** args,
            gint args_length1)
{
	MainWindow* app = NULL;
	MainWindow* _tmp0_;
	gint result = 0;
#line 6 "src/postmayne.vala"
	gtk_init ((gint*) (&args_length1), &args);
#line 8 "src/postmayne.vala"
	_tmp0_ = main_window_new ();
#line 8 "src/postmayne.vala"
	g_object_ref_sink (_tmp0_);
#line 8 "src/postmayne.vala"
	app = _tmp0_;
#line 9 "src/postmayne.vala"
	gtk_widget_show_all ((GtkWidget*) app);
#line 10 "src/postmayne.vala"
	g_signal_connect ((GtkWidget*) app, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
#line 12 "src/postmayne.vala"
	gtk_main ();
#line 14 "src/postmayne.vala"
	result = 0;
#line 14 "src/postmayne.vala"
	_g_object_unref0 (app);
#line 14 "src/postmayne.vala"
	return result;
#line 128 "postmayne.c"
}

int
main (int argc,
      char ** argv)
{
#line 5 "src/postmayne.vala"
	return _vala_main (argv, argc);
#line 137 "postmayne.c"
}

static inline gpointer
main_window_get_instance_private (MainWindow* self)
{
	return G_STRUCT_MEMBER_P (self, MainWindow_private_offset);
}

static void
_main_window_on_send_clicked_gtk_button_clicked (GtkButton* _sender,
                                                 gpointer self)
{
#line 63 "src/postmayne.vala"
	main_window_on_send_clicked ((MainWindow*) self);
#line 152 "postmayne.c"
}

static void
_main_window_add_request_header_row_gtk_button_clicked (GtkButton* _sender,
                                                        gpointer self)
{
#line 77 "src/postmayne.vala"
	main_window_add_request_header_row ((MainWindow*) self);
#line 161 "postmayne.c"
}

MainWindow*
main_window_construct (GType object_type)
{
	MainWindow * self = NULL;
	GtkHeaderBar* header = NULL;
	GtkHeaderBar* _tmp0_;
	GtkHeaderBar* _tmp1_;
	GtkHeaderBar* _tmp2_;
	GtkHeaderBar* _tmp3_;
	const gchar* _tmp4_;
	const gchar* _tmp5_;
	GtkHeaderBar* _tmp6_;
	GtkComboBoxText* _tmp7_;
	GtkComboBoxText* _tmp11_;
	GtkEntry* _tmp12_;
	GtkEntry* _tmp13_;
	GtkButton* send_button = NULL;
	GtkButton* _tmp14_;
	GtkBox* primary_controls = NULL;
	GtkBox* _tmp15_;
	GtkComboBoxText* _tmp16_;
	GtkEntry* _tmp17_;
	GtkBox* request_header_container = NULL;
	GtkBox* _tmp18_;
	GtkBox* request_header_controls_heading_container = NULL;
	GtkBox* _tmp19_;
	GtkLabel* request_header_controls_heading_label = NULL;
	GtkLabel* _tmp20_;
	GtkButton* request_header_add_button = NULL;
	GtkButton* _tmp21_;
	GtkGrid* _tmp22_;
	GtkGrid* _tmp23_;
	GtkGrid* _tmp24_;
	GtkGrid* _tmp25_;
	GtkGrid* _tmp26_;
	GtkGrid* _tmp27_;
	GtkBox* request_body_container = NULL;
	GtkBox* _tmp28_;
	GtkBox* request_body_content_type_container = NULL;
	GtkBox* _tmp29_;
	GtkLabel* request_body_content_type_label = NULL;
	GtkLabel* _tmp30_;
	GtkEntry* _tmp31_;
	GtkEntry* _tmp32_;
	GtkTextView* _tmp33_;
	GtkScrolledWindow* request_body_scrolled_window = NULL;
	GtkScrolledWindow* _tmp34_;
	GtkTextView* _tmp35_;
	GtkTextView* _tmp36_;
	GtkTextView* _tmp37_;
	GtkTextView* _tmp38_;
	GtkScrolledWindow* response_body_scrolled_window = NULL;
	GtkScrolledWindow* _tmp39_;
	GtkTextView* _tmp40_;
	GtkBox* vbox = NULL;
	GtkBox* _tmp41_;
#line 40 "src/postmayne.vala"
	self = (MainWindow*) g_object_new (object_type, NULL);
#line 41 "src/postmayne.vala"
	gtk_window_set_title ((GtkWindow*) self, "Postmayne");
#line 42 "src/postmayne.vala"
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER, NULL);
#line 43 "src/postmayne.vala"
	gtk_window_set_default_size ((GtkWindow*) self, 640, 480);
#line 45 "src/postmayne.vala"
	_tmp0_ = (GtkHeaderBar*) gtk_header_bar_new ();
#line 45 "src/postmayne.vala"
	g_object_ref_sink (_tmp0_);
#line 45 "src/postmayne.vala"
	header = _tmp0_;
#line 46 "src/postmayne.vala"
	_tmp1_ = header;
#line 46 "src/postmayne.vala"
	gtk_header_bar_set_has_subtitle (_tmp1_, FALSE);
#line 47 "src/postmayne.vala"
	_tmp2_ = header;
#line 47 "src/postmayne.vala"
	gtk_header_bar_set_show_close_button (_tmp2_, TRUE);
#line 48 "src/postmayne.vala"
	_tmp3_ = header;
#line 48 "src/postmayne.vala"
	_tmp4_ = gtk_window_get_title ((GtkWindow*) self);
#line 48 "src/postmayne.vala"
	_tmp5_ = _tmp4_;
#line 48 "src/postmayne.vala"
	gtk_header_bar_set_title (_tmp3_, _tmp5_);
#line 49 "src/postmayne.vala"
	_tmp6_ = header;
#line 49 "src/postmayne.vala"
	gtk_window_set_titlebar ((GtkWindow*) self, (GtkWidget*) _tmp6_);
#line 53 "src/postmayne.vala"
	_tmp7_ = (GtkComboBoxText*) gtk_combo_box_text_new ();
#line 53 "src/postmayne.vala"
	g_object_ref_sink (_tmp7_);
#line 53 "src/postmayne.vala"
	_g_object_unref0 (self->priv->request_method_combo);
#line 53 "src/postmayne.vala"
	self->priv->request_method_combo = _tmp7_;
#line 262 "postmayne.c"
	{
		const gchar** method_collection = NULL;
		gint method_collection_length1 = 0;
		gint _method_collection_size_ = 0;
		gint method_it = 0;
#line 54 "src/postmayne.vala"
		method_collection = MAIN_WINDOW_REQUEST_METHODS;
#line 54 "src/postmayne.vala"
		method_collection_length1 = G_N_ELEMENTS (MAIN_WINDOW_REQUEST_METHODS);
#line 54 "src/postmayne.vala"
		for (method_it = 0; method_it < method_collection_length1; method_it = method_it + 1) {
#line 274 "postmayne.c"
			gchar* _tmp8_;
			gchar* method = NULL;
#line 54 "src/postmayne.vala"
			_tmp8_ = g_strdup (method_collection[method_it]);
#line 54 "src/postmayne.vala"
			method = _tmp8_;
#line 281 "postmayne.c"
			{
				GtkComboBoxText* _tmp9_;
				const gchar* _tmp10_;
#line 55 "src/postmayne.vala"
				_tmp9_ = self->priv->request_method_combo;
#line 55 "src/postmayne.vala"
				_tmp10_ = method;
#line 55 "src/postmayne.vala"
				gtk_combo_box_text_append_text (_tmp9_, _tmp10_);
#line 54 "src/postmayne.vala"
				_g_free0 (method);
#line 293 "postmayne.c"
			}
		}
	}
#line 57 "src/postmayne.vala"
	_tmp11_ = self->priv->request_method_combo;
#line 57 "src/postmayne.vala"
	gtk_combo_box_set_active ((GtkComboBox*) _tmp11_, 0);
#line 59 "src/postmayne.vala"
	_tmp12_ = (GtkEntry*) gtk_entry_new ();
#line 59 "src/postmayne.vala"
	g_object_ref_sink (_tmp12_);
#line 59 "src/postmayne.vala"
	_g_object_unref0 (self->priv->url_entry);
#line 59 "src/postmayne.vala"
	self->priv->url_entry = _tmp12_;
#line 60 "src/postmayne.vala"
	_tmp13_ = self->priv->url_entry;
#line 60 "src/postmayne.vala"
	gtk_entry_set_input_purpose (_tmp13_, GTK_INPUT_PURPOSE_URL);
#line 62 "src/postmayne.vala"
	_tmp14_ = (GtkButton*) gtk_button_new_with_label ("Send");
#line 62 "src/postmayne.vala"
	g_object_ref_sink (_tmp14_);
#line 62 "src/postmayne.vala"
	send_button = _tmp14_;
#line 63 "src/postmayne.vala"
	g_signal_connect_object (send_button, "clicked", (GCallback) _main_window_on_send_clicked_gtk_button_clicked, self, 0);
#line 65 "src/postmayne.vala"
	_tmp15_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 2);
#line 65 "src/postmayne.vala"
	g_object_ref_sink (_tmp15_);
#line 65 "src/postmayne.vala"
	primary_controls = _tmp15_;
#line 66 "src/postmayne.vala"
	_tmp16_ = self->priv->request_method_combo;
#line 66 "src/postmayne.vala"
	gtk_box_pack_start (primary_controls, (GtkWidget*) _tmp16_, FALSE, FALSE, (guint) 2);
#line 67 "src/postmayne.vala"
	_tmp17_ = self->priv->url_entry;
#line 67 "src/postmayne.vala"
	gtk_box_pack_start (primary_controls, (GtkWidget*) _tmp17_, TRUE, TRUE, (guint) 2);
#line 68 "src/postmayne.vala"
	gtk_box_pack_end (primary_controls, (GtkWidget*) send_button, FALSE, FALSE, (guint) 2);
#line 72 "src/postmayne.vala"
	_tmp18_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 2);
#line 72 "src/postmayne.vala"
	g_object_ref_sink (_tmp18_);
#line 72 "src/postmayne.vala"
	request_header_container = _tmp18_;
#line 74 "src/postmayne.vala"
	_tmp19_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 2);
#line 74 "src/postmayne.vala"
	g_object_ref_sink (_tmp19_);
#line 74 "src/postmayne.vala"
	request_header_controls_heading_container = _tmp19_;
#line 75 "src/postmayne.vala"
	_tmp20_ = (GtkLabel*) gtk_label_new ("Request Headers");
#line 75 "src/postmayne.vala"
	g_object_ref_sink (_tmp20_);
#line 75 "src/postmayne.vala"
	request_header_controls_heading_label = _tmp20_;
#line 76 "src/postmayne.vala"
	_tmp21_ = (GtkButton*) gtk_button_new_with_label ("Add");
#line 76 "src/postmayne.vala"
	g_object_ref_sink (_tmp21_);
#line 76 "src/postmayne.vala"
	request_header_add_button = _tmp21_;
#line 77 "src/postmayne.vala"
	g_signal_connect_object (request_header_add_button, "clicked", (GCallback) _main_window_add_request_header_row_gtk_button_clicked, self, 0);
#line 79 "src/postmayne.vala"
	gtk_box_pack_start (request_header_controls_heading_container, (GtkWidget*) request_header_controls_heading_label, FALSE, FALSE, (guint) 2);
#line 80 "src/postmayne.vala"
	gtk_box_pack_end (request_header_controls_heading_container, (GtkWidget*) request_header_add_button, FALSE, FALSE, (guint) 2);
#line 81 "src/postmayne.vala"
	gtk_box_pack_start (request_header_container, (GtkWidget*) request_header_controls_heading_container, TRUE, TRUE, (guint) 2);
#line 83 "src/postmayne.vala"
	_tmp22_ = (GtkGrid*) gtk_grid_new ();
#line 83 "src/postmayne.vala"
	g_object_ref_sink (_tmp22_);
#line 83 "src/postmayne.vala"
	_g_object_unref0 (self->priv->request_header_grid);
#line 83 "src/postmayne.vala"
	self->priv->request_header_grid = _tmp22_;
#line 84 "src/postmayne.vala"
	_tmp23_ = self->priv->request_header_grid;
#line 84 "src/postmayne.vala"
	gtk_grid_insert_row (_tmp23_, 0);
#line 85 "src/postmayne.vala"
	_tmp24_ = self->priv->request_header_grid;
#line 85 "src/postmayne.vala"
	gtk_grid_insert_column (_tmp24_, 0);
#line 86 "src/postmayne.vala"
	_tmp25_ = self->priv->request_header_grid;
#line 86 "src/postmayne.vala"
	gtk_grid_insert_column (_tmp25_, 1);
#line 87 "src/postmayne.vala"
	_tmp26_ = self->priv->request_header_grid;
#line 87 "src/postmayne.vala"
	gtk_grid_insert_column (_tmp26_, 2);
#line 88 "src/postmayne.vala"
	main_window_add_request_header_row (self);
#line 90 "src/postmayne.vala"
	_tmp27_ = self->priv->request_header_grid;
#line 90 "src/postmayne.vala"
	gtk_box_pack_start (request_header_container, (GtkWidget*) _tmp27_, TRUE, TRUE, (guint) 2);
#line 94 "src/postmayne.vala"
	_tmp28_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 2);
#line 94 "src/postmayne.vala"
	g_object_ref_sink (_tmp28_);
#line 94 "src/postmayne.vala"
	request_body_container = _tmp28_;
#line 96 "src/postmayne.vala"
	_tmp29_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 2);
#line 96 "src/postmayne.vala"
	g_object_ref_sink (_tmp29_);
#line 96 "src/postmayne.vala"
	request_body_content_type_container = _tmp29_;
#line 97 "src/postmayne.vala"
	_tmp30_ = (GtkLabel*) gtk_label_new ("Content Type");
#line 97 "src/postmayne.vala"
	g_object_ref_sink (_tmp30_);
#line 97 "src/postmayne.vala"
	request_body_content_type_label = _tmp30_;
#line 98 "src/postmayne.vala"
	_tmp31_ = (GtkEntry*) gtk_entry_new ();
#line 98 "src/postmayne.vala"
	g_object_ref_sink (_tmp31_);
#line 98 "src/postmayne.vala"
	_g_object_unref0 (self->priv->request_body_content_type_entry);
#line 98 "src/postmayne.vala"
	self->priv->request_body_content_type_entry = _tmp31_;
#line 99 "src/postmayne.vala"
	gtk_box_pack_start (request_body_content_type_container, (GtkWidget*) request_body_content_type_label, FALSE, FALSE, (guint) 2);
#line 100 "src/postmayne.vala"
	_tmp32_ = self->priv->request_body_content_type_entry;
#line 100 "src/postmayne.vala"
	gtk_box_pack_start (request_body_content_type_container, (GtkWidget*) _tmp32_, TRUE, TRUE, (guint) 2);
#line 102 "src/postmayne.vala"
	_tmp33_ = (GtkTextView*) gtk_text_view_new ();
#line 102 "src/postmayne.vala"
	g_object_ref_sink (_tmp33_);
#line 102 "src/postmayne.vala"
	_g_object_unref0 (self->priv->request_body_text_view);
#line 102 "src/postmayne.vala"
	self->priv->request_body_text_view = _tmp33_;
#line 103 "src/postmayne.vala"
	_tmp34_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 103 "src/postmayne.vala"
	g_object_ref_sink (_tmp34_);
#line 103 "src/postmayne.vala"
	request_body_scrolled_window = _tmp34_;
#line 104 "src/postmayne.vala"
	gtk_scrolled_window_set_policy (request_body_scrolled_window, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
#line 105 "src/postmayne.vala"
	_tmp35_ = self->priv->request_body_text_view;
#line 105 "src/postmayne.vala"
	gtk_container_add ((GtkContainer*) request_body_scrolled_window, (GtkWidget*) _tmp35_);
#line 107 "src/postmayne.vala"
	gtk_box_pack_start (request_body_container, (GtkWidget*) request_body_content_type_container, FALSE, FALSE, (guint) 2);
#line 108 "src/postmayne.vala"
	gtk_box_pack_start (request_body_container, (GtkWidget*) request_body_scrolled_window, TRUE, TRUE, (guint) 2);
#line 112 "src/postmayne.vala"
	_tmp36_ = (GtkTextView*) gtk_text_view_new ();
#line 112 "src/postmayne.vala"
	g_object_ref_sink (_tmp36_);
#line 112 "src/postmayne.vala"
	_g_object_unref0 (self->priv->response_body_text_view);
#line 112 "src/postmayne.vala"
	self->priv->response_body_text_view = _tmp36_;
#line 113 "src/postmayne.vala"
	_tmp37_ = self->priv->response_body_text_view;
#line 113 "src/postmayne.vala"
	gtk_text_view_set_editable (_tmp37_, FALSE);
#line 114 "src/postmayne.vala"
	_tmp38_ = self->priv->response_body_text_view;
#line 114 "src/postmayne.vala"
	gtk_text_view_set_cursor_visible (_tmp38_, FALSE);
#line 116 "src/postmayne.vala"
	_tmp39_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 116 "src/postmayne.vala"
	g_object_ref_sink (_tmp39_);
#line 116 "src/postmayne.vala"
	response_body_scrolled_window = _tmp39_;
#line 117 "src/postmayne.vala"
	gtk_scrolled_window_set_policy (response_body_scrolled_window, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
#line 118 "src/postmayne.vala"
	_tmp40_ = self->priv->response_body_text_view;
#line 118 "src/postmayne.vala"
	gtk_container_add ((GtkContainer*) response_body_scrolled_window, (GtkWidget*) _tmp40_);
#line 122 "src/postmayne.vala"
	_tmp41_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 2);
#line 122 "src/postmayne.vala"
	g_object_ref_sink (_tmp41_);
#line 122 "src/postmayne.vala"
	vbox = _tmp41_;
#line 123 "src/postmayne.vala"
	gtk_box_pack_start (vbox, (GtkWidget*) primary_controls, FALSE, TRUE, (guint) 2);
#line 124 "src/postmayne.vala"
	gtk_box_pack_start (vbox, (GtkWidget*) request_header_container, FALSE, TRUE, (guint) 2);
#line 125 "src/postmayne.vala"
	gtk_box_pack_start (vbox, (GtkWidget*) request_body_container, TRUE, TRUE, (guint) 2);
#line 126 "src/postmayne.vala"
	gtk_box_pack_start (vbox, (GtkWidget*) response_body_scrolled_window, TRUE, TRUE, (guint) 2);
#line 128 "src/postmayne.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) vbox);
#line 40 "src/postmayne.vala"
	_g_object_unref0 (vbox);
#line 40 "src/postmayne.vala"
	_g_object_unref0 (response_body_scrolled_window);
#line 40 "src/postmayne.vala"
	_g_object_unref0 (request_body_scrolled_window);
#line 40 "src/postmayne.vala"
	_g_object_unref0 (request_body_content_type_label);
#line 40 "src/postmayne.vala"
	_g_object_unref0 (request_body_content_type_container);
#line 40 "src/postmayne.vala"
	_g_object_unref0 (request_body_container);
#line 40 "src/postmayne.vala"
	_g_object_unref0 (request_header_add_button);
#line 40 "src/postmayne.vala"
	_g_object_unref0 (request_header_controls_heading_label);
#line 40 "src/postmayne.vala"
	_g_object_unref0 (request_header_controls_heading_container);
#line 40 "src/postmayne.vala"
	_g_object_unref0 (request_header_container);
#line 40 "src/postmayne.vala"
	_g_object_unref0 (primary_controls);
#line 40 "src/postmayne.vala"
	_g_object_unref0 (send_button);
#line 40 "src/postmayne.vala"
	_g_object_unref0 (header);
#line 40 "src/postmayne.vala"
	return self;
#line 527 "postmayne.c"
}

MainWindow*
main_window_new (void)
{
#line 40 "src/postmayne.vala"
	return main_window_construct (TYPE_MAIN_WINDOW);
#line 535 "postmayne.c"
}

static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
#line 131 "src/postmayne.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 131 "src/postmayne.vala"
	return _data1_;
#line 545 "postmayne.c"
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 131 "src/postmayne.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 555 "postmayne.c"
		MainWindow* self;
#line 131 "src/postmayne.vala"
		self = _data1_->self;
#line 131 "src/postmayne.vala"
		_g_object_unref0 (_data1_->header_delete_button);
#line 131 "src/postmayne.vala"
		_g_object_unref0 (self);
#line 131 "src/postmayne.vala"
		g_slice_free (Block1Data, _data1_);
#line 565 "postmayne.c"
	}
}

static void
__lambda4_ (Block1Data* _data1_)
{
	MainWindow* self;
#line 135 "src/postmayne.vala"
	self = _data1_->self;
#line 136 "src/postmayne.vala"
	main_window_remove_request_header_row (self, (GtkWidget*) _data1_->header_delete_button);
#line 577 "postmayne.c"
}

static void
___lambda4__gtk_button_clicked (GtkButton* _sender,
                                gpointer self)
{
#line 135 "src/postmayne.vala"
	__lambda4_ (self);
#line 586 "postmayne.c"
}

static void
main_window_add_request_header_row (MainWindow* self)
{
	Block1Data* _data1_;
	GtkEntry* header_key_entry = NULL;
	GtkEntry* _tmp0_;
	GtkEntry* header_value_entry = NULL;
	GtkEntry* _tmp1_;
	GtkButton* _tmp2_;
	GtkGrid* _tmp3_;
	GtkGrid* _tmp4_;
	GtkGrid* _tmp5_;
	GtkGrid* _tmp6_;
	GtkGrid* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
#line 131 "src/postmayne.vala"
	g_return_if_fail (self != NULL);
#line 131 "src/postmayne.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 131 "src/postmayne.vala"
	_data1_->_ref_count_ = 1;
#line 131 "src/postmayne.vala"
	_data1_->self = g_object_ref (self);
#line 132 "src/postmayne.vala"
	_tmp0_ = (GtkEntry*) gtk_entry_new ();
#line 132 "src/postmayne.vala"
	g_object_ref_sink (_tmp0_);
#line 132 "src/postmayne.vala"
	header_key_entry = _tmp0_;
#line 133 "src/postmayne.vala"
	_tmp1_ = (GtkEntry*) gtk_entry_new ();
#line 133 "src/postmayne.vala"
	g_object_ref_sink (_tmp1_);
#line 133 "src/postmayne.vala"
	header_value_entry = _tmp1_;
#line 134 "src/postmayne.vala"
	_tmp2_ = (GtkButton*) gtk_button_new_with_label ("Remove");
#line 134 "src/postmayne.vala"
	g_object_ref_sink (_tmp2_);
#line 134 "src/postmayne.vala"
	_data1_->header_delete_button = _tmp2_;
#line 135 "src/postmayne.vala"
	g_signal_connect_data (_data1_->header_delete_button, "clicked", (GCallback) ___lambda4__gtk_button_clicked, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 139 "src/postmayne.vala"
	_tmp3_ = self->priv->request_header_grid;
#line 139 "src/postmayne.vala"
	gtk_grid_insert_row (_tmp3_, 0);
#line 140 "src/postmayne.vala"
	_tmp4_ = self->priv->request_header_grid;
#line 140 "src/postmayne.vala"
	gtk_grid_attach (_tmp4_, (GtkWidget*) header_key_entry, 0, 0, 1, 1);
#line 141 "src/postmayne.vala"
	_tmp5_ = self->priv->request_header_grid;
#line 141 "src/postmayne.vala"
	gtk_grid_attach (_tmp5_, (GtkWidget*) header_value_entry, 1, 0, 1, 1);
#line 142 "src/postmayne.vala"
	_tmp6_ = self->priv->request_header_grid;
#line 142 "src/postmayne.vala"
	gtk_grid_attach (_tmp6_, (GtkWidget*) _data1_->header_delete_button, 2, 0, 1, 1);
#line 143 "src/postmayne.vala"
	_tmp7_ = self->priv->request_header_grid;
#line 143 "src/postmayne.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp7_);
#line 144 "src/postmayne.vala"
	self->priv->request_header_grid_size = self->priv->request_header_grid_size + 1;
#line 145 "src/postmayne.vala"
	_tmp8_ = g_strdup_printf ("%i", self->priv->request_header_grid_size);
#line 145 "src/postmayne.vala"
	_tmp9_ = _tmp8_;
#line 145 "src/postmayne.vala"
	_tmp10_ = g_strconcat (_tmp9_, "\n", NULL);
#line 145 "src/postmayne.vala"
	_tmp11_ = _tmp10_;
#line 145 "src/postmayne.vala"
	g_print ("%s", _tmp11_);
#line 145 "src/postmayne.vala"
	_g_free0 (_tmp11_);
#line 145 "src/postmayne.vala"
	_g_free0 (_tmp9_);
#line 131 "src/postmayne.vala"
	_g_object_unref0 (header_value_entry);
#line 131 "src/postmayne.vala"
	_g_object_unref0 (header_key_entry);
#line 131 "src/postmayne.vala"
	block1_data_unref (_data1_);
#line 131 "src/postmayne.vala"
	_data1_ = NULL;
#line 679 "postmayne.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 150 "src/postmayne.vala"
	return self ? g_object_ref (self) : NULL;
#line 687 "postmayne.c"
}

static void
main_window_remove_request_header_row (MainWindow* self,
                                       GtkWidget* header_delete_button)
{
#line 148 "src/postmayne.vala"
	g_return_if_fail (self != NULL);
#line 148 "src/postmayne.vala"
	g_return_if_fail (header_delete_button != NULL);
#line 698 "postmayne.c"
	{
		gint i = 0;
#line 149 "src/postmayne.vala"
		i = 0;
#line 703 "postmayne.c"
		{
			gboolean _tmp0_ = FALSE;
#line 149 "src/postmayne.vala"
			_tmp0_ = TRUE;
#line 149 "src/postmayne.vala"
			while (TRUE) {
#line 710 "postmayne.c"
				GtkWidget* widget = NULL;
				GtkGrid* _tmp2_;
				GtkWidget* _tmp3_;
				GtkWidget* _tmp4_;
				GtkWidget* _tmp5_;
#line 149 "src/postmayne.vala"
				if (!_tmp0_) {
#line 718 "postmayne.c"
					gint _tmp1_;
#line 149 "src/postmayne.vala"
					_tmp1_ = i;
#line 149 "src/postmayne.vala"
					i = _tmp1_ + 1;
#line 724 "postmayne.c"
				}
#line 149 "src/postmayne.vala"
				_tmp0_ = FALSE;
#line 149 "src/postmayne.vala"
				if (!(i < self->priv->request_header_grid_size)) {
#line 149 "src/postmayne.vala"
					break;
#line 732 "postmayne.c"
				}
#line 150 "src/postmayne.vala"
				_tmp2_ = self->priv->request_header_grid;
#line 150 "src/postmayne.vala"
				_tmp3_ = gtk_grid_get_child_at (_tmp2_, 2, i);
#line 150 "src/postmayne.vala"
				_tmp4_ = _g_object_ref0 (_tmp3_);
#line 150 "src/postmayne.vala"
				widget = _tmp4_;
#line 151 "src/postmayne.vala"
				_tmp5_ = widget;
#line 151 "src/postmayne.vala"
				if (_tmp5_ == header_delete_button) {
#line 746 "postmayne.c"
					GtkGrid* _tmp6_;
					gchar* _tmp7_;
					gchar* _tmp8_;
					gchar* _tmp9_;
					gchar* _tmp10_;
#line 152 "src/postmayne.vala"
					_tmp6_ = self->priv->request_header_grid;
#line 152 "src/postmayne.vala"
					gtk_grid_remove_row (_tmp6_, i);
#line 153 "src/postmayne.vala"
					self->priv->request_header_grid_size = self->priv->request_header_grid_size - 1;
#line 154 "src/postmayne.vala"
					_tmp7_ = g_strdup_printf ("%i", self->priv->request_header_grid_size);
#line 154 "src/postmayne.vala"
					_tmp8_ = _tmp7_;
#line 154 "src/postmayne.vala"
					_tmp9_ = g_strconcat (_tmp8_, "\n", NULL);
#line 154 "src/postmayne.vala"
					_tmp10_ = _tmp9_;
#line 154 "src/postmayne.vala"
					g_print ("%s", _tmp10_);
#line 154 "src/postmayne.vala"
					_g_free0 (_tmp10_);
#line 154 "src/postmayne.vala"
					_g_free0 (_tmp8_);
#line 155 "src/postmayne.vala"
					_g_object_unref0 (widget);
#line 155 "src/postmayne.vala"
					return;
#line 776 "postmayne.c"
				}
#line 149 "src/postmayne.vala"
				_g_object_unref0 (widget);
#line 780 "postmayne.c"
			}
		}
	}
#line 158 "src/postmayne.vala"
	g_print ("Couldn't delete request header row for some reason\n");
#line 786 "postmayne.c"
}

static guint8*
string_get_data (const gchar* self,
                 gint* result_length1)
{
	guint8* result;
	guint8* res = NULL;
	gint res_length1;
	gint _res_size_;
	gint _tmp0_;
	gint _tmp1_;
	guint8* _tmp2_;
	gint _tmp2__length1;
#line 1501 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1502 "glib-2.0.vapi"
	res = (guint8*) self;
#line 1502 "glib-2.0.vapi"
	res_length1 = -1;
#line 1502 "glib-2.0.vapi"
	_res_size_ = res_length1;
#line 1503 "glib-2.0.vapi"
	_tmp0_ = strlen (self);
#line 1503 "glib-2.0.vapi"
	_tmp1_ = _tmp0_;
#line 1503 "glib-2.0.vapi"
	res_length1 = (gint) _tmp1_;
#line 1504 "glib-2.0.vapi"
	_tmp2_ = res;
#line 1504 "glib-2.0.vapi"
	_tmp2__length1 = res_length1;
#line 1504 "glib-2.0.vapi"
	if (result_length1) {
#line 1504 "glib-2.0.vapi"
		*result_length1 = _tmp2__length1;
#line 823 "postmayne.c"
	}
#line 1504 "glib-2.0.vapi"
	result = _tmp2_;
#line 1504 "glib-2.0.vapi"
	return result;
#line 829 "postmayne.c"
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result = NULL;
#line 1516 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1517 "glib-2.0.vapi"
	result = self;
#line 1517 "glib-2.0.vapi"
	return result;
#line 842 "postmayne.c"
}

static void
_main_window_on_http_request_complete_soup_session_callback (SoupSession* session,
                                                             SoupMessage* msg,
                                                             gpointer self)
{
#line 203 "src/postmayne.vala"
	main_window_on_http_request_complete ((MainWindow*) self, session, msg);
#line 203 "src/postmayne.vala"
	g_object_unref (self);
#line 854 "postmayne.c"
}

static void
main_window_on_send_clicked (MainWindow* self)
{
	SoupSession* session = NULL;
	SoupSession* _tmp0_;
	SoupLogger* logger = NULL;
	SoupLogger* _tmp1_;
	SoupSession* _tmp2_;
	SoupLogger* _tmp3_;
	SoupMessage* message = NULL;
	GtkComboBoxText* _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	GtkEntry* _tmp7_;
	const gchar* _tmp8_;
	SoupMessage* _tmp9_;
	SoupMessage* _tmp10_;
	GtkTextView* _tmp11_;
	GtkTextBuffer* _tmp12_;
	GtkTextBuffer* _tmp13_;
	SoupMessage* _tmp65_;
	gchar* _tmp66_;
	gchar* _tmp67_;
	gchar* _tmp68_;
	const gchar* _tmp69_;
	SoupMessage* _tmp70_;
	SoupURI* _tmp71_;
	SoupURI* _tmp72_;
	gchar* _tmp73_;
	gchar* _tmp74_;
	const gchar* _tmp75_;
	gchar* _tmp76_;
	gchar* _tmp77_;
	SoupSession* _tmp78_;
	SoupMessage* _tmp79_;
	SoupMessage* _tmp80_;
#line 161 "src/postmayne.vala"
	g_return_if_fail (self != NULL);
#line 162 "src/postmayne.vala"
	_tmp0_ = soup_session_new ();
#line 162 "src/postmayne.vala"
	session = _tmp0_;
#line 163 "src/postmayne.vala"
	_tmp1_ = soup_logger_new (SOUP_LOGGER_LOG_MINIMAL, -1);
#line 163 "src/postmayne.vala"
	logger = _tmp1_;
#line 164 "src/postmayne.vala"
	_tmp2_ = session;
#line 164 "src/postmayne.vala"
	_tmp3_ = logger;
#line 164 "src/postmayne.vala"
	soup_session_add_feature (_tmp2_, (SoupSessionFeature*) _tmp3_);
#line 166 "src/postmayne.vala"
	_tmp4_ = self->priv->request_method_combo;
#line 166 "src/postmayne.vala"
	_tmp5_ = gtk_combo_box_text_get_active_text (_tmp4_);
#line 166 "src/postmayne.vala"
	_tmp6_ = _tmp5_;
#line 166 "src/postmayne.vala"
	_tmp7_ = self->priv->url_entry;
#line 166 "src/postmayne.vala"
	_tmp8_ = gtk_entry_get_text (_tmp7_);
#line 166 "src/postmayne.vala"
	_tmp9_ = soup_message_new (_tmp6_, _tmp8_);
#line 166 "src/postmayne.vala"
	_tmp10_ = _tmp9_;
#line 166 "src/postmayne.vala"
	_g_free0 (_tmp6_);
#line 166 "src/postmayne.vala"
	message = _tmp10_;
#line 169 "src/postmayne.vala"
	_tmp11_ = self->priv->request_body_text_view;
#line 169 "src/postmayne.vala"
	_tmp12_ = gtk_text_view_get_buffer (_tmp11_);
#line 169 "src/postmayne.vala"
	_tmp13_ = _tmp12_;
#line 169 "src/postmayne.vala"
	if (gtk_text_buffer_get_char_count (_tmp13_) > 0) {
#line 935 "postmayne.c"
		GtkEntry* _tmp14_;
		const gchar* _tmp15_;
		gint _tmp16_;
		gint _tmp17_;
		gchar* data = NULL;
		GtkTextView* _tmp21_;
		GtkTextBuffer* _tmp22_;
		GtkTextBuffer* _tmp23_;
		gchar* _tmp24_;
		gchar* _tmp25_;
		const gchar* _tmp26_;
		SoupMessage* _tmp27_;
		GtkEntry* _tmp28_;
		const gchar* _tmp29_;
		const gchar* _tmp30_;
		guint8* _tmp31_;
		gint _tmp31__length1;
		guint8* _tmp32_;
		gint _tmp32__length1;
#line 170 "src/postmayne.vala"
		_tmp14_ = self->priv->request_body_content_type_entry;
#line 170 "src/postmayne.vala"
		_tmp15_ = gtk_entry_get_text (_tmp14_);
#line 170 "src/postmayne.vala"
		_tmp16_ = strlen (_tmp15_);
#line 170 "src/postmayne.vala"
		_tmp17_ = _tmp16_;
#line 170 "src/postmayne.vala"
		if (_tmp17_ < 1) {
#line 965 "postmayne.c"
			GtkTextView* _tmp18_;
			GtkTextBuffer* _tmp19_;
			GtkTextBuffer* _tmp20_;
#line 171 "src/postmayne.vala"
			g_print ("Can't send a request body without content-type.");
#line 172 "src/postmayne.vala"
			_tmp18_ = self->priv->response_body_text_view;
#line 172 "src/postmayne.vala"
			_tmp19_ = gtk_text_view_get_buffer (_tmp18_);
#line 172 "src/postmayne.vala"
			_tmp20_ = _tmp19_;
#line 172 "src/postmayne.vala"
			gtk_text_buffer_set_text (_tmp20_, "Can't send a request body without content-type.", -1);
#line 173 "src/postmayne.vala"
			_g_object_unref0 (message);
#line 173 "src/postmayne.vala"
			_g_object_unref0 (logger);
#line 173 "src/postmayne.vala"
			_g_object_unref0 (session);
#line 173 "src/postmayne.vala"
			return;
#line 987 "postmayne.c"
		}
#line 175 "src/postmayne.vala"
		_tmp21_ = self->priv->request_body_text_view;
#line 175 "src/postmayne.vala"
		_tmp22_ = gtk_text_view_get_buffer (_tmp21_);
#line 175 "src/postmayne.vala"
		_tmp23_ = _tmp22_;
#line 175 "src/postmayne.vala"
		g_object_get (_tmp23_, "text", &_tmp24_, NULL);
#line 175 "src/postmayne.vala"
		_tmp25_ = _tmp24_;
#line 175 "src/postmayne.vala"
		data = _tmp25_;
#line 177 "src/postmayne.vala"
		_tmp26_ = data;
#line 177 "src/postmayne.vala"
		g_print ("%s", (const gchar*) _tmp26_);
#line 179 "src/postmayne.vala"
		_tmp27_ = message;
#line 179 "src/postmayne.vala"
		_tmp28_ = self->priv->request_body_content_type_entry;
#line 179 "src/postmayne.vala"
		_tmp29_ = gtk_entry_get_text (_tmp28_);
#line 179 "src/postmayne.vala"
		_tmp30_ = data;
#line 179 "src/postmayne.vala"
		_tmp31_ = string_get_data (_tmp30_, &_tmp31__length1);
#line 179 "src/postmayne.vala"
		_tmp32_ = _tmp31_;
#line 179 "src/postmayne.vala"
		_tmp32__length1 = _tmp31__length1;
#line 179 "src/postmayne.vala"
		soup_message_set_request (_tmp27_, _tmp29_, SOUP_MEMORY_COPY, _tmp32_, (gsize) _tmp32__length1);
#line 169 "src/postmayne.vala"
		_g_free0 (data);
#line 1023 "postmayne.c"
	}
	{
		gint i = 0;
#line 186 "src/postmayne.vala"
		i = 0;
#line 1029 "postmayne.c"
		{
			gboolean _tmp33_ = FALSE;
#line 186 "src/postmayne.vala"
			_tmp33_ = TRUE;
#line 186 "src/postmayne.vala"
			while (TRUE) {
#line 1036 "postmayne.c"
				GtkEntry* key_entry = NULL;
				GtkGrid* _tmp35_;
				GtkWidget* _tmp36_;
				GtkEntry* _tmp37_;
				GtkEntry* val_entry = NULL;
				GtkGrid* _tmp38_;
				GtkWidget* _tmp39_;
				GtkEntry* _tmp40_;
				gboolean _tmp41_ = FALSE;
				GtkEntry* _tmp42_;
				gchar* key = NULL;
				GtkEntry* _tmp44_;
				const gchar* _tmp45_;
				gchar* _tmp46_;
				gchar* val = NULL;
				GtkEntry* _tmp47_;
				const gchar* _tmp48_;
				gchar* _tmp49_;
				gboolean _tmp50_ = FALSE;
				gboolean _tmp51_ = FALSE;
				gboolean _tmp52_ = FALSE;
				const gchar* _tmp53_;
				SoupMessage* _tmp61_;
				SoupMessageHeaders* _tmp62_;
				const gchar* _tmp63_;
				const gchar* _tmp64_;
#line 186 "src/postmayne.vala"
				if (!_tmp33_) {
#line 1065 "postmayne.c"
					gint _tmp34_;
#line 186 "src/postmayne.vala"
					_tmp34_ = i;
#line 186 "src/postmayne.vala"
					i = _tmp34_ + 1;
#line 1071 "postmayne.c"
				}
#line 186 "src/postmayne.vala"
				_tmp33_ = FALSE;
#line 186 "src/postmayne.vala"
				if (!(i < self->priv->request_header_grid_size)) {
#line 186 "src/postmayne.vala"
					break;
#line 1079 "postmayne.c"
				}
#line 187 "src/postmayne.vala"
				_tmp35_ = self->priv->request_header_grid;
#line 187 "src/postmayne.vala"
				_tmp36_ = gtk_grid_get_child_at (_tmp35_, 0, i);
#line 187 "src/postmayne.vala"
				_tmp37_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp36_, gtk_entry_get_type (), GtkEntry));
#line 187 "src/postmayne.vala"
				key_entry = _tmp37_;
#line 188 "src/postmayne.vala"
				_tmp38_ = self->priv->request_header_grid;
#line 188 "src/postmayne.vala"
				_tmp39_ = gtk_grid_get_child_at (_tmp38_, 1, i);
#line 188 "src/postmayne.vala"
				_tmp40_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (_tmp39_, gtk_entry_get_type (), GtkEntry));
#line 188 "src/postmayne.vala"
				val_entry = _tmp40_;
#line 189 "src/postmayne.vala"
				_tmp42_ = key_entry;
#line 189 "src/postmayne.vala"
				if (_tmp42_ == NULL) {
#line 189 "src/postmayne.vala"
					_tmp41_ = TRUE;
#line 1103 "postmayne.c"
				} else {
					GtkEntry* _tmp43_;
#line 189 "src/postmayne.vala"
					_tmp43_ = val_entry;
#line 189 "src/postmayne.vala"
					_tmp41_ = _tmp43_ == NULL;
#line 1110 "postmayne.c"
				}
#line 189 "src/postmayne.vala"
				if (_tmp41_) {
#line 190 "src/postmayne.vala"
					_g_object_unref0 (val_entry);
#line 190 "src/postmayne.vala"
					_g_object_unref0 (key_entry);
#line 190 "src/postmayne.vala"
					continue;
#line 1120 "postmayne.c"
				}
#line 193 "src/postmayne.vala"
				_tmp44_ = key_entry;
#line 193 "src/postmayne.vala"
				_tmp45_ = gtk_entry_get_text (_tmp44_);
#line 193 "src/postmayne.vala"
				_tmp46_ = g_strdup (_tmp45_);
#line 193 "src/postmayne.vala"
				key = _tmp46_;
#line 194 "src/postmayne.vala"
				_tmp47_ = val_entry;
#line 194 "src/postmayne.vala"
				_tmp48_ = gtk_entry_get_text (_tmp47_);
#line 194 "src/postmayne.vala"
				_tmp49_ = g_strdup (_tmp48_);
#line 194 "src/postmayne.vala"
				val = _tmp49_;
#line 195 "src/postmayne.vala"
				_tmp53_ = key;
#line 195 "src/postmayne.vala"
				if (_tmp53_ == NULL) {
#line 195 "src/postmayne.vala"
					_tmp52_ = TRUE;
#line 1144 "postmayne.c"
				} else {
					const gchar* _tmp54_;
					gint _tmp55_;
					gint _tmp56_;
#line 195 "src/postmayne.vala"
					_tmp54_ = key;
#line 195 "src/postmayne.vala"
					_tmp55_ = strlen (_tmp54_);
#line 195 "src/postmayne.vala"
					_tmp56_ = _tmp55_;
#line 195 "src/postmayne.vala"
					_tmp52_ = _tmp56_ < 1;
#line 1157 "postmayne.c"
				}
#line 195 "src/postmayne.vala"
				if (_tmp52_) {
#line 195 "src/postmayne.vala"
					_tmp51_ = TRUE;
#line 1163 "postmayne.c"
				} else {
					const gchar* _tmp57_;
#line 195 "src/postmayne.vala"
					_tmp57_ = val;
#line 195 "src/postmayne.vala"
					_tmp51_ = _tmp57_ == NULL;
#line 1170 "postmayne.c"
				}
#line 195 "src/postmayne.vala"
				if (_tmp51_) {
#line 195 "src/postmayne.vala"
					_tmp50_ = TRUE;
#line 1176 "postmayne.c"
				} else {
					const gchar* _tmp58_;
					gint _tmp59_;
					gint _tmp60_;
#line 195 "src/postmayne.vala"
					_tmp58_ = val;
#line 195 "src/postmayne.vala"
					_tmp59_ = strlen (_tmp58_);
#line 195 "src/postmayne.vala"
					_tmp60_ = _tmp59_;
#line 195 "src/postmayne.vala"
					_tmp50_ = _tmp60_ < 1;
#line 1189 "postmayne.c"
				}
#line 195 "src/postmayne.vala"
				if (_tmp50_) {
#line 196 "src/postmayne.vala"
					_g_free0 (val);
#line 196 "src/postmayne.vala"
					_g_free0 (key);
#line 196 "src/postmayne.vala"
					_g_object_unref0 (val_entry);
#line 196 "src/postmayne.vala"
					_g_object_unref0 (key_entry);
#line 196 "src/postmayne.vala"
					continue;
#line 1203 "postmayne.c"
				}
#line 199 "src/postmayne.vala"
				_tmp61_ = message;
#line 199 "src/postmayne.vala"
				_tmp62_ = _tmp61_->request_headers;
#line 199 "src/postmayne.vala"
				_tmp63_ = key;
#line 199 "src/postmayne.vala"
				_tmp64_ = val;
#line 199 "src/postmayne.vala"
				soup_message_headers_append (_tmp62_, _tmp63_, _tmp64_);
#line 186 "src/postmayne.vala"
				_g_free0 (val);
#line 186 "src/postmayne.vala"
				_g_free0 (key);
#line 186 "src/postmayne.vala"
				_g_object_unref0 (val_entry);
#line 186 "src/postmayne.vala"
				_g_object_unref0 (key_entry);
#line 1223 "postmayne.c"
			}
		}
	}
#line 202 "src/postmayne.vala"
	_tmp65_ = message;
#line 202 "src/postmayne.vala"
	g_object_get (_tmp65_, "method", &_tmp66_, NULL);
#line 202 "src/postmayne.vala"
	_tmp67_ = _tmp66_;
#line 202 "src/postmayne.vala"
	_tmp68_ = _tmp67_;
#line 202 "src/postmayne.vala"
	_tmp69_ = string_to_string (_tmp68_);
#line 202 "src/postmayne.vala"
	_tmp70_ = message;
#line 202 "src/postmayne.vala"
	_tmp71_ = soup_message_get_uri (_tmp70_);
#line 202 "src/postmayne.vala"
	_tmp72_ = _tmp71_;
#line 202 "src/postmayne.vala"
	_tmp73_ = soup_uri_to_string (_tmp72_, FALSE);
#line 202 "src/postmayne.vala"
	_tmp74_ = _tmp73_;
#line 202 "src/postmayne.vala"
	_tmp75_ = string_to_string (_tmp74_);
#line 202 "src/postmayne.vala"
	_tmp76_ = g_strconcat (_tmp69_, " ", _tmp75_, NULL);
#line 202 "src/postmayne.vala"
	_tmp77_ = _tmp76_;
#line 202 "src/postmayne.vala"
	g_print ("%s", _tmp77_);
#line 202 "src/postmayne.vala"
	_g_free0 (_tmp77_);
#line 202 "src/postmayne.vala"
	_g_free0 (_tmp74_);
#line 202 "src/postmayne.vala"
	_g_free0 (_tmp68_);
#line 203 "src/postmayne.vala"
	_tmp78_ = session;
#line 203 "src/postmayne.vala"
	_tmp79_ = message;
#line 203 "src/postmayne.vala"
	_tmp80_ = _g_object_ref0 (_tmp79_);
#line 203 "src/postmayne.vala"
	soup_session_queue_message (_tmp78_, _tmp80_, _main_window_on_http_request_complete_soup_session_callback, g_object_ref (self));
#line 161 "src/postmayne.vala"
	_g_object_unref0 (message);
#line 161 "src/postmayne.vala"
	_g_object_unref0 (logger);
#line 161 "src/postmayne.vala"
	_g_object_unref0 (session);
#line 1275 "postmayne.c"
}

static void
main_window_on_http_request_complete (MainWindow* self,
                                      SoupSession* session,
                                      SoupMessage* message)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gchar* response_body = NULL;
	SoupMessageBody* _tmp8_;
	guint8* _tmp9_;
	gint _tmp9__length1;
	gchar* _tmp10_;
	const gchar* _tmp11_;
	gint _tmp12_;
	gint _tmp13_;
	gchar* response_body_normalized = NULL;
	const gchar* _tmp17_;
	gchar* _tmp18_;
	const gchar* _tmp19_;
#line 206 "src/postmayne.vala"
	g_return_if_fail (self != NULL);
#line 206 "src/postmayne.vala"
	g_return_if_fail (session != NULL);
#line 206 "src/postmayne.vala"
	g_return_if_fail (message != NULL);
#line 207 "src/postmayne.vala"
	if (message == NULL) {
#line 207 "src/postmayne.vala"
		_tmp1_ = TRUE;
#line 1307 "postmayne.c"
	} else {
		SoupMessageBody* _tmp2_;
#line 207 "src/postmayne.vala"
		_tmp2_ = message->response_body;
#line 207 "src/postmayne.vala"
		_tmp1_ = _tmp2_ == NULL;
#line 1314 "postmayne.c"
	}
#line 207 "src/postmayne.vala"
	if (_tmp1_) {
#line 207 "src/postmayne.vala"
		_tmp0_ = TRUE;
#line 1320 "postmayne.c"
	} else {
		SoupMessageBody* _tmp3_;
		guint8* _tmp4_;
		gint _tmp4__length1;
#line 207 "src/postmayne.vala"
		_tmp3_ = message->response_body;
#line 207 "src/postmayne.vala"
		_tmp4_ = _tmp3_->data;
#line 207 "src/postmayne.vala"
		_tmp4__length1 = _tmp3_->length;
#line 207 "src/postmayne.vala"
		_tmp0_ = _tmp4_ == NULL;
#line 1333 "postmayne.c"
	}
#line 207 "src/postmayne.vala"
	if (_tmp0_) {
#line 1337 "postmayne.c"
		GtkTextView* _tmp5_;
		GtkTextBuffer* _tmp6_;
		GtkTextBuffer* _tmp7_;
#line 208 "src/postmayne.vala"
		_tmp5_ = self->priv->response_body_text_view;
#line 208 "src/postmayne.vala"
		_tmp6_ = gtk_text_view_get_buffer (_tmp5_);
#line 208 "src/postmayne.vala"
		_tmp7_ = _tmp6_;
#line 208 "src/postmayne.vala"
		gtk_text_buffer_set_text (_tmp7_, "No response body", -1);
#line 209 "src/postmayne.vala"
		return;
#line 1351 "postmayne.c"
	}
#line 212 "src/postmayne.vala"
	_tmp8_ = message->response_body;
#line 212 "src/postmayne.vala"
	_tmp9_ = _tmp8_->data;
#line 212 "src/postmayne.vala"
	_tmp9__length1 = _tmp8_->length;
#line 212 "src/postmayne.vala"
	_tmp10_ = g_strdup ((const gchar*) _tmp9_);
#line 212 "src/postmayne.vala"
	response_body = _tmp10_;
#line 214 "src/postmayne.vala"
	_tmp11_ = response_body;
#line 214 "src/postmayne.vala"
	_tmp12_ = strlen (_tmp11_);
#line 214 "src/postmayne.vala"
	_tmp13_ = _tmp12_;
#line 214 "src/postmayne.vala"
	if (_tmp13_ < 1) {
#line 1371 "postmayne.c"
		GtkTextView* _tmp14_;
		GtkTextBuffer* _tmp15_;
		GtkTextBuffer* _tmp16_;
#line 215 "src/postmayne.vala"
		_tmp14_ = self->priv->response_body_text_view;
#line 215 "src/postmayne.vala"
		_tmp15_ = gtk_text_view_get_buffer (_tmp14_);
#line 215 "src/postmayne.vala"
		_tmp16_ = _tmp15_;
#line 215 "src/postmayne.vala"
		gtk_text_buffer_set_text (_tmp16_, "No response body", -1);
#line 216 "src/postmayne.vala"
		_g_free0 (response_body);
#line 216 "src/postmayne.vala"
		return;
#line 1387 "postmayne.c"
	}
#line 219 "src/postmayne.vala"
	_tmp17_ = response_body;
#line 219 "src/postmayne.vala"
	_tmp18_ = g_utf8_normalize (_tmp17_, (gssize) -1, G_NORMALIZE_DEFAULT);
#line 219 "src/postmayne.vala"
	response_body_normalized = _tmp18_;
#line 221 "src/postmayne.vala"
	_tmp19_ = response_body_normalized;
#line 221 "src/postmayne.vala"
	if (_tmp19_ == NULL) {
#line 1399 "postmayne.c"
		GtkTextView* _tmp20_;
		GtkTextBuffer* _tmp21_;
		GtkTextBuffer* _tmp22_;
		const gchar* _tmp23_;
		gchar* _tmp24_;
		gchar* _tmp25_;
#line 222 "src/postmayne.vala"
		_tmp20_ = self->priv->response_body_text_view;
#line 222 "src/postmayne.vala"
		_tmp21_ = gtk_text_view_get_buffer (_tmp20_);
#line 222 "src/postmayne.vala"
		_tmp22_ = _tmp21_;
#line 222 "src/postmayne.vala"
		_tmp23_ = response_body;
#line 222 "src/postmayne.vala"
		_tmp24_ = g_str_to_ascii (_tmp23_, NULL);
#line 222 "src/postmayne.vala"
		_tmp25_ = _tmp24_;
#line 222 "src/postmayne.vala"
		gtk_text_buffer_set_text (_tmp22_, _tmp25_, -1);
#line 222 "src/postmayne.vala"
		_g_free0 (_tmp25_);
#line 1422 "postmayne.c"
	} else {
		GtkTextView* _tmp26_;
		GtkTextBuffer* _tmp27_;
		GtkTextBuffer* _tmp28_;
		const gchar* _tmp29_;
#line 224 "src/postmayne.vala"
		_tmp26_ = self->priv->response_body_text_view;
#line 224 "src/postmayne.vala"
		_tmp27_ = gtk_text_view_get_buffer (_tmp26_);
#line 224 "src/postmayne.vala"
		_tmp28_ = _tmp27_;
#line 224 "src/postmayne.vala"
		_tmp29_ = response_body_normalized;
#line 224 "src/postmayne.vala"
		gtk_text_buffer_set_text (_tmp28_, _tmp29_, -1);
#line 1438 "postmayne.c"
	}
#line 206 "src/postmayne.vala"
	_g_free0 (response_body_normalized);
#line 206 "src/postmayne.vala"
	_g_free0 (response_body);
#line 1444 "postmayne.c"
}

static void
main_window_class_init (MainWindowClass * klass,
                        gpointer klass_data)
{
#line 17 "src/postmayne.vala"
	main_window_parent_class = g_type_class_peek_parent (klass);
#line 17 "src/postmayne.vala"
	g_type_class_adjust_private_offset (klass, &MainWindow_private_offset);
#line 17 "src/postmayne.vala"
	G_OBJECT_CLASS (klass)->finalize = main_window_finalize;
#line 1457 "postmayne.c"
}

static void
main_window_instance_init (MainWindow * self,
                           gpointer klass)
{
#line 17 "src/postmayne.vala"
	self->priv = main_window_get_instance_private (self);
#line 23 "src/postmayne.vala"
	self->priv->request_header_grid_size = 0;
#line 1468 "postmayne.c"
}

static void
main_window_finalize (GObject * obj)
{
	MainWindow * self;
#line 17 "src/postmayne.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN_WINDOW, MainWindow);
#line 18 "src/postmayne.vala"
	_g_object_unref0 (self->priv->response_body_text_view);
#line 19 "src/postmayne.vala"
	_g_object_unref0 (self->priv->request_method_combo);
#line 20 "src/postmayne.vala"
	_g_object_unref0 (self->priv->url_entry);
#line 22 "src/postmayne.vala"
	_g_object_unref0 (self->priv->request_header_grid);
#line 25 "src/postmayne.vala"
	_g_object_unref0 (self->priv->request_body_content_type_entry);
#line 26 "src/postmayne.vala"
	_g_object_unref0 (self->priv->request_body_text_view);
#line 17 "src/postmayne.vala"
	G_OBJECT_CLASS (main_window_parent_class)->finalize (obj);
#line 1491 "postmayne.c"
}

GType
main_window_get_type (void)
{
	static volatile gsize main_window_type_id__volatile = 0;
	if (g_once_init_enter (&main_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MainWindow), 0, (GInstanceInitFunc) main_window_instance_init, NULL };
		GType main_window_type_id;
		main_window_type_id = g_type_register_static (gtk_window_get_type (), "MainWindow", &g_define_type_info, 0);
		MainWindow_private_offset = g_type_add_instance_private (main_window_type_id, sizeof (MainWindowPrivate));
		g_once_init_leave (&main_window_type_id__volatile, main_window_type_id);
	}
	return main_window_type_id__volatile;
}

